# fly.toml app configuration file generated for shared-shopping-ui on 2024-04-06T12:59:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shared-shopping-ui'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
